system:
  log_level: INFO
  device: cuda          # Use 'cuda' for GPU, 'cpu' for CPU or 'mps' for Mac

paths:
  input_video: data/input/video_1.mp4
  output_video: data/output/output.avi
  stub_path: stubs/     # Directory to save/load .pkl files for fast debugging

models:
  player_tracker:
    model_path: models/yolov8x.pt         # Standard YOLOv8x for person detection
    confidence_threshold: 0.25
    
  ball_tracker:
    model_path: models/yolov8x_ball_trained.pt # Your fine-tuned ball model
    confidence_threshold: 0.15            # Keep low for fast-moving objects
    
  court_detector:
    model_path: models/model_tennis_court_det.pt

video:
  fps: 24.0